### ISSUE TITLE
Allow addition of PubMed ID to submission manuscript

### ISSUE THREAD

**Issue by jstewart-ebi** [EBISPOT/gwasdepo-deposition-service#2]
@jstewart-ebi commented on [Mon Mar 16 2020](https://github.com/EBISPOT/goci/issues/40)

Curator and submitter users need the ability to associate a PubMed ID with a previously submitted publication. The endpoint should allow the update of a manuscript and add a PubMed ID to it.

**Comment by twhetzel** [comment]
@jstewart-ebi is the plan that this endpoint will be the one that the Deposition UI calls to allow a submitter to add a PMID to an existing submission? I thought the PMID update by submitter would be handled by an endpoint in the https://github.com/EBISPOT/gwas-deposition-backend/tree/master/gdapp-backend-service repo.

**Comment by tudorgroza** [comment]
@twhetzel - (side note) that repo is no longer in use. Will retire it in the next month.

I will add a `PUT` on `/manuscripts` (to continue the API started here: https://docs.google.com/document/d/11gdSglClAJTvZ5QH8qxspI2s-JxgGIariof2SwSi7Ho/edit) - since the `PMID` is nothing else than just a property of the manuscript.
